---
- name: Ensure ACL installed (for Ansible become)
  ansible.builtin.package:
    name:
      - acl
    state: present

- name: Create storage dir
  ansible.builtin.file:
    path: "{{ podman_storage_path }}"
    state: directory
    owner: "{{ podman_user }}"
    group: root
    mode: "u=rwx,g=,o="

- name: Deploy storage.conf
  ansible.builtin.template:
    src: "storage.conf.j2"
    dest: "~{{ podman_user }}/.config/containers/storage.conf"
    owner: "{{ podman_user }}"
    group: "root"
    mode: "u=rw,g=,o="
  when: "podman_storage_path is defined"

- name: Check for existence of bind directories
  ansible.builtin.stat:
    path: "{{ item.path }}"
  register: podman_mount_dirs
  with_items: "{{ podman_mounts }}"

- name: Create bind directories
  ansible.builtin.file:
    path: "{{ item.item.path }}"
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: "{{ item.item.mode | default('u=rwX,g=rX,o=')}}"
    state: directory
  with_items: "{{ podman_mount_dirs.results }}"
  when: not item.stat.exists
  register: bind_mnt_created

- name: Set owner/group on bind directories
  ansible.builtin.command:
    argv:
      - podman
      - unshare
      - chown
      # note the lack of -R
      - "{{ item.uid }}:{{ item.gid }}"
      - "{{ item.path }}"
  with_items: "{{ podman_mounts }}"
  become_user: "{{ podman_user }}"
  become: true
  changed_when: true
  when: bind_mnt_created.changed
