---
argument_specs:
  main:
    short_description: "Radicale container."
    author: "dogeystamp <dogeystamp@disroot.org>"
    options:
      radicale_data_path:
        description: "Bind-mount path for Radicale data; this will be created by the role."
        type: "path"
        required: true

      radicale_config_path:
        description: "Bind-mount path for Radicale config; this will be created by the role."
        type: "path"
        required: true

      radicale_users:
        description: "List of users for Radicale authentication."
        type: "list"
        default: []
        options:
          name:
            description: "Username."
            type: "str"
            required: true
          hash:
            description: "Password hash."
            type: "str"
            required: true
